### ISSUE TITLE
Missing Some Widgets...

### ISSUE THREAD

**Issue by aminwhat** [Flutter-Swap/dart#1]
Hi there, I found out that some widgets like Scaffold are not in the Swap Package Base,
Other Widgets are just Copied from Flutter Source into the Swap,

Is there any reason technical reason for that?
Am I Missing Something?

**Comment by subzero911** [comment]
> Hi there, I found out that some widgets like Scaffold are not in the Swap Package Base

Aloïs told in his presentation at Flutter Connection 2024 that SDUI is not quite good for creating a page hierarchy on the spot or replacing the whole app. It's supposed to have a predefined app screens with a dynamic content. So you won't need a Scaffold.
